

spring:
  profiles:
    active: native
  application:
    name: configServer
  server:
    port: 8888
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations
